public: false
type: "docs"
tags:
  - "digital preservation"
  - "processing"
  - "digital media log"
title: "Digital Media Transfer Workflow"
description: "Instructions for inventorying and transferring digital media, using the Digital Media Log"
pages:
  - ["Rockefeller Archive Center Digital Media Transfer Workflow", "index"]
  - ["Inventorying Digital Media", "inventory"]
  - ["Transfer Instructions by Digital Media Type", "transfer-instructions"]
  - ["Virus Scan", "virus_scan]
  - ["Troubleshooting by Digital Media Type", "troubleshooting"]
