public: false
type: "docs"
category: "preservation"
tags:
  - "digital preservation"
  - "processing"
  - "digital media log"
title: "Digital Media Transfer Workflow"
description: "Instructions for inventorying and transferring digital media, using the Digital Media Log"
pages:
  - ["Rockefeller Archive Center Digital Media Transfer Workflow", "index"]
  - ["Inventorying Digital Media", "inventory"]
  - ["Transfer Instructions", "transfer-instructions"]
  - ["Scanning for Viruses", "virus_scan"]
  - ["Troubleshooting by Digital Media Type", "troubleshooting"]
  - ["Error Reporting", "error_reporting"]
