public: true
type: "docs"
category: "preservation"
tags:
  - "workflow"
title: "Digital Media Transfer Workflow"
description: "Instructions for inventorying and transferring digital media, using the Digital Media Log"
pages:
  - ["Digital Media Transfer Workflow", "index"]
  - ["Inventorying Digital Media", "inventory"]
  - ["Transfer Instructions", "transfer-instructions"]
  - ["Scanning for Viruses", "virus_scan"]
  - ["Troubleshooting", "troubleshooting"]
